### ISSUE TITLE
Nollup's rollup optimizations hurt performance

### ISSUE THREAD

**Issue by nstepien** [PepsRyuu/nollup#138] opened 2020-08-23 16:36 UTC
From the README:

>Using Rollup in development can be incredibly slow with rebuilds taking seconds because of all of the optimisations Rollup does for you (ie. tree-shaking, scope-hoisting).

This ends up resulting in HUGE entry/chunk scripts for me:

![image](https://user-images.githubusercontent.com/567105/90983233-7fb0b980-e564-11ea-9e7b-43ed6dfde9ef.png)

(notice the size of those scripts)

![image](https://user-images.githubusercontent.com/567105/90983284-c9010900-e564-11ea-9369-be4a67b16d2b.png)

7s to evaluate!!! I'm not on a slow machine or anything.

The `NotFound` chunk should be really tiny, instead it seems to include all the dependencies that should have been tree-shaken, or at least be hoisted up to the entry chunk.

I think [`@material-ui/icons` with its 1100+ svg icons](https://material-ui.com/components/material-icons/) is partly to blame, but it shouldn't be an issue with tree-shaking enabled.
![image](https://user-images.githubusercontent.com/567105/90983361-7116d200-e565-11ea-89a8-2fe7ebf9d863.png)

---

Is it possible to keep rollup's configuration as close as possible to the defaults?

FWIW:
- With nollup I get a ~2 minutes initial build, then ~1s for rebuilds.
- With `rollup ... --watch` I get a \~1min 15s initial build, then 4~6s for rebuilds (not too bad IMO).
Booting up nollup is slower than I would expect.

**Comment by PepsRyuu** [comment] 2020-08-23 18:34
Tree-shaking is a very expensive feature to implement, as the entire code based has to be scanned to determine what variables are used and what aren't. To keep things really fast, all Nollup cares about is what code is imported and what isn't, and by not performing the optimisations, it gains a lot of speed for initial builds and rebuilds enabling real-time development. Tree-shaking won't be implemented for that reason.

In this particular situation, the issue is that the library is not well implemented in my opinion. They really shouldn't have an index file that contains every single icon, as it's going to lead to several mistakes by developers. Other libraries like Moment have a similar problem where they include every locale in by default that result in large bundle sizes.

According to the material-ui documentation, icons should either be imported individually by their files:

```
import IconName from '@material-ui/icons/esm/IconName';
```

Or optionally, if using the index file approach, their docs also states that you need to use a Babel plugin to avoid all icons being included: https://material-ui.com/guides/minimizing-bundle-size/#option-2

**Comment by nstepien** [comment] 2020-08-23 18:51
>Tree-shaking won't be implemented for that reason.

I though rollup was used under the hood. So nollup re-implements rollup to some extent?
I wish there was single rollup plugin that would give a dev server + hmr/fast-refresh. 🥺 

>They really shouldn't have an index file that contains every single icon, as it's going to lead to several mistakes by developers.

It hasn't been an issue in practice for me.

>you need to use a Babel plugin to avoid all icons being included

It's a lot of work/maintenance to do this for all potential (sub)dependencies that would benefit from this IMO.

**Comment by PepsRyuu** [comment] 2020-08-23 19:09
Unfortunately the Rollup plugin architecture doesn't really allow for a fast developer experience (I tried, trust me!) as the architecture is fundamentally different to the point they're incompatible. As a result, the configuration and plugin API is re-implemented in Nollup but with the development experience in mind. :)

**Comment by nstepien** [comment] 2020-08-23 20:05
Has there been any discussion with the rollup team to allow for this kind of dev-server to work as a plugin?
Personally I would prefer a dev experience that's a bit closer to the prod experience, at the cost of build times. There's probably still room for perf improvements in rollup's internals, so I'm not too worried about it.
Re-implementing rollup as nollup is a lot of work I'm sure, I really respect that. I feel like it's unfortunate that it has to be done that way though, it's a lot of duplicated effort in a sense.

**Comment by PepsRyuu** [comment] 2020-08-24 09:44
It's not possible without changing the entire architecture, nor do I think it makes a lot of sense to be in a plugin anyways, as it causes messy configuration and would likely lead to significant performance problems because the plugin system is designed for transforming file assets, as opposed to injecting developer tooling. Providing features like HMR efficiently and for quick rebuilds requires full control over the pipeline. 

Development tools will always be slightly inconsistent to production, there's no working around that. In Webpack for example, the dev bundles are entirely different from the production bundles, and plugins will behave very differently whether or not you're running in development or production. Babel plugins inject development runtimes (like React Refresh), as well as other things like environment variables. That possibility can never be eliminated, but in terms of accuracy for Nollup's implementation, for the most common features, should be pretty much identical in behaviour, and there's hundreds of test cases that help to ensure consistency.

One thing I would like to see is a library that provides the plugin runtime, as that's really the only thing that's duplicated. I have no idea how something like that would work though. It would also help other new developer tools that re-implement a small subset of the Rollup plugin API so that they can re-use the plugins.

**Closed** 2020-08-24 09:44 UTC
