### ISSUE TITLE
firebase.auth is not a function

### ISSUE THREAD

**Issue by kierangilliam** [PepsRyuu/nollup#107] opened 2020-07-15 00:06 UTC
I'm using Firebase in a project. I believe there is some issue when using nollup and the firebase imports: `import 'firebase/auth'` and `import 'firebase/analytics'`. When I run the following with nollup I get the error: 

`Uncaught (in promise) TypeError: firebase.auth is not a function`

```
<script lang='ts'>
    import { onMount } from 'svelte'
    import * as firebase from 'firebase/app'
    import 'firebase/auth'
    import 'firebase/analytics'
    import { Authorization } from '@state'
    import { authInitialized } from './utils'

    const config = {
        ...
    }

    onMount(async () => {
        firebase.initializeApp(config)
        $authInitialized = true

        firebase.auth().onAuthStateChanged(function(user) {
            firebase.analytics()
            let idToken 

            if (user) {
                idToken = user.getIdToken.toString()
            } 

            $Authorization = idToken ? `Bearer ${idToken}` : null
        });
    })
</script>
```

However, when I run using plain rollup, I do not get this error. Any ideas?

**Comment by PepsRyuu** [comment] 2020-07-15 07:59
Can you provide a reproducible example? Just trying it out, and I'm getting the same result between Nollup and Rollup.

![image](https://user-images.githubusercontent.com/6637882/87518767-9ff17c80-c678-11ea-9d20-36b07c5e5013.png)

![image](https://user-images.githubusercontent.com/6637882/87518822-aa137b00-c678-11ea-84b8-9818d2253fed.png)

For the code to work, you should switch from namespace import to default import for ```firebase/app```. It doesn't export any named properties at all. 

```
import firebase from 'firebase/app';
```

**Comment by PepsRyuu** [comment] 2020-07-15 08:15
Upon further digging, this seems to be some weird documentation / TypeScript problem with Firebase:

https://github.com/firebase/firebase-js-sdk/issues/3315#issuecomment-653872699
https://github.com/firebase/firebase-js-sdk/issues/1832
https://github.com/firebase/firebase-js-sdk/issues/1008#issuecomment-405219175

Not entirely sure what's going on, but it sounds like their documentation assumes you're using TypeScript, and that TypeScript has a different behaviour for resolving namespace imports. I think TypeScript has a flag that allows the namespace import to work even though it's a default export. Very weird and goes against the ESM spec.

**Comment by kierangilliam** [comment] 2020-07-17 00:56
[Here's a minimal example](https://github.com/kierangilliam/firebase-error-example). Run `yarn dev` for normal rollup, and `yarn dev:nollup` for nollup.

Rollup will throw an error because there's no config, but it loads firebase correctly.

**Comment by PepsRyuu** [comment] 2020-07-17 17:59
Running dev for Rollup doesn't show me anything but "Cannot GET /" :(

**Closed** 2021-03-17 18:41 UTC
