### ISSUE TITLE
React demo

### ISSUE THREAD

**Issue by vzaidman** [PepsRyuu/nollup#11] opened 2018-11-15 07:30 UTC
I'm trying to make react-hot-loader in my project work.

I'll be glad to improve `nollup` to achieve it as well.

please take a look:
https://github.com/welldone-software/why-did-you-render/tree/react-hot-loader
`react-hot-loader` tree

I followed the steps suggested but it doesn't seem to work or error.

I'll be glad for someone suggesting what's the problem there.

In the end we will have a React project example (yey! :D )

**Comment by vzaidman** [comment] 2018-11-15 08:34
ill remove the lodash plugin and import the whole thing on development

**Comment by vzaidman** [comment] 2018-11-15 08:40
ok it helped.
now i dont undestand where the build is outputted. (`app._hash_.js`)
`demo/dist` doesnt seem to be created.

**Comment by PepsRyuu** [comment] 2018-11-15 10:21
Hmmm. I think I missed a few steps in the documentation.

I'll do a proper investigation of this as soon as I can. :)

**Comment by vzaidman** [comment] 2018-11-15 10:32
great. ill be glad to help. i developed some webpack plugins :)
tell me if you have any new ideas

**Comment by PepsRyuu** [comment] 2018-11-15 10:39
Few things I can say for sure:

* You need to update index.html to point to ```demo/dist/app._hash_.js```. :)
* ```export * from <file>``` doesn't seem to be working. I don't have test cases for this, but it should be trivial to add support for it.
* I think I modified ```react-hot-loader.development.cjs.js``` to use ```import``` instead of ```require``` but I can't remember the full details.

A lot of these problems are a result of ```rollup-plugin-commonjs```. I was considering perhaps forking it or implementing a custom version of the plugin that handles ```require``` calls in a way that more closely aligns with how Webpack does it. A lot of the problems stems from that. With a proper commonjs plugin, we can simplify the steps significantly. I'm sure though the team behind that plugin have their reasons though as to why they made certain decisions.

**Comment by vzaidman** [comment] 2018-11-15 14:05
* we statically serve `demo/dist` so i think it's ok.
* it doesn't seem to emit anything
* i modified it just like you wrote in the example. it looks fine.

**Comment by PepsRyuu** [comment] 2018-11-15 23:50
Updates:

I published a new version of nollup (0.2.2) which adds support for ```export * from <file>``` statements. 

For the ```demo/dist``` thing, nollup doesn't actually create any files. It's all served from memory. As a result, ```express.static``` won't do anything because there's no static files to be served. The generated bundle according to the config will be generated at "http://localhost:3030/demo/dist/app._hash_.js". Sounds like I might need to add an option to nollup-dev-server to allow for custom base paths. Open to suggestions on this one. 

I decided to try and prototype a new plugin that will take care of some of the issues surrounding React Hot Loader. This new plugin converts CommonJS modules into a format that nollup can accept. This works with nollup perfectly, but need to do additional work to get it working with Rollup. I think it's a viable solution though. I've attached an updated example project that uses this new plugin, but build will fail at the moment.

[react-hmr-example.zip](https://github.com/PepsRyuu/nollup/files/2587442/react-hmr-example.zip)

**Comment by vzaidman** [comment] 2018-11-16 08:02
i wonder how come the default export doesn't gets to the application:
it is exported like this:
![image](https://user-images.githubusercontent.com/5188459/48605777-638eea00-e986-11e8-8c29-0b47c24cd16b.png)
i tried to import it like this:
![image](https://user-images.githubusercontent.com/5188459/48605818-828d7c00-e986-11e8-8e22-0efb31e136bf.png)
but i dont get the right object in the end.
is it overridden somehow?
![image](https://user-images.githubusercontent.com/5188459/48605857-9f29b400-e986-11e8-90c7-2f07a13f636b.png)
i wrote a small test that i thought would help but it passes and i expected it to fail (`import-default-from-es`)
https://github.com/PepsRyuu/nollup/pull/12

**Comment by PepsRyuu** [comment] 2018-11-16 08:37
Default exports is a bit weird.

Like with Rollup, Nollup has no understanding of CommonJS. The core will be focus on ES modules, and will prioritise that. So that means if you import with the default syntax, it will look for an exported default property. If you import all, it will just give you all of the export properties. Those test cases actually work as intended and closely aligns with the ESM specification (except for live-bindings which I intentionally left out).

Here's why default exports with CommonJS are a nightmare:

* Typically people import React as ```import React from 'react';```. This means that ES module parsers will look for the ```default``` property from react. Looking at React code, it doesn't exist. It also doesn't contain the __esModule keyword. The solution here would be to remap ```module.exports = X``` to ```export default X```.

* What if an object is exported? ```module.exports = { X, Y, Z }```, in this scenario, we've an ambiguity. If we remap this to ```export default { X, Y, Z }```, then we can import it using a default syntax. However, what if we wanted to get ```X``` from the exported object? Using React as an example, a common syntax people like to use is ```import React, { X } from 'react';```, but X doesn't exist as an export. It's a property on the default export (```module.exports.default = { X, Y, Z }```).

* Who does the importing also matters. If we're importing using ```require()```, then the intent is quite clear. If we're importing using ```import```, then we have the ambiguity. In my prototype plugin I attached previously, it works around this problem by exporting the ```default``` property, and also by doing the original export. This is incompatible with Rollup though as Rollup is looking for ES exports.

* Something like __esModule could help a little bit, since it helps make some of the behaviour less ambiguous. But a lot of CJS modules don't include that, including React, which means we have an ambiguity.

For Webpack, they can easily get away with this, because they started with CJS, and can simply just convert ESM to CJS which is a trivial transformation since you're going from a static standard to a dynamic format. For Rollup, since it started with ESM, it's much more challenging to convert a dynamic format to a static format. Since we don't execute the code, we have to rely on static analysis to determine what the appropriate way to remap the CJS exports is. 

Hope that helps clarify what's going on!

**Comment by PepsRyuu** [comment] 2018-11-18 19:33
I pushed a React Hot Loader example to the master branch. :)

https://github.com/PepsRyuu/nollup/tree/master/examples/example-react-hot-loader

**Comment by vzaidman** [comment] 2018-11-22 18:43
thanks!!!
updated my branch!
https://github.com/welldone-software/why-did-you-render/tree/react-hot-loader

now, it works to the point where the demo is running. but the hot reload doesnt seem to happen.

can you take a look?

also, regarding the commonjs plugin, any intention to publish it?

**Comment by PepsRyuu** [comment] 2018-11-22 23:00
There was a minor mistake in the invalidate function. Path wasn't being calculated correctly. I tested it on your branch and it worked for me. Released 0.2.3 to fix this. https://github.com/PepsRyuu/nollup/commit/fa4361d405cfb0a4cff60d2bb39b91b8a1db119a

I hadn't actually considered publishing it! 😅 There's still a few issues with it I want to address before making a first version, namely the RHL conditional magic, and the named exports configuration. It'll be a few days before I get a proper chance to look into it, but it's certainly something I can look into. 🙂

**Comment by PepsRyuu** [comment] 2018-11-23 08:38
Excellent! Enjoy! :D

This is just for reference, done some further research into what needs to be done for the CommonJS plugin for release. For the conditional require magic in RHL, turns out Parcel has the exact same problem handling it: https://github.com/parcel-bundler/parcel/issues/1593 . And this is how Webpack solves it.... https://github.com/webpack/webpack/blob/master/lib/Parser.js

Going to need to think about this one!

**Comment by PepsRyuu** [comment] 2018-12-06 22:10
Both plugins released as separate libraries:

https://www.npmjs.com/package/rollup-plugin-hot-css
https://www.npmjs.com/package/rollup-plugin-commonjs-alternate

Examples have been updated to use these new plugins:

https://github.com/PepsRyuu/nollup/blob/master/examples/example-react-hot-loader/rollup.config.js

Enjoy! :)

**Closed by PepsRyuu** 2018-12-06 22:10 UTC
