### ISSUE TITLE
Ignore falsy plugins as per rollup documentation

### ISSUE THREAD

**Issue by ankon** [PepsRyuu/nollup#51] opened 2019-11-15 13:06 UTC
Rollup is explicit about ignoring falsy plugins:
> See Using plugins for more information on how to use plugins and Plugins on how to write your own (try it out, it's not as difficult as it may sound and very much extends what you can do with Rollup). For plugins imported from packages, remember to call the imported plugin function (i.e. commonjs(), not just commonjs). **Falsy plugins will be ignored, which can be used to easily activate or deactivate plugins.**

(see https://rollupjs.org/guide/en/#plugins)

I quickly tried nollup on our project now, and noticed that it stumbled over such a situation. A quick patch as below made it go further, but then gets stuck on other, more problematic uses in our setup.

As this is only lightly tested: Not a PR, but a starting point of a patch instead:
```diff
diff --git a/lib/cli.js b/lib/cli.js
old mode 100644
new mode 100755
diff --git a/lib/impl/NollupContext.js b/lib/impl/NollupContext.js
index f755836..d989aa7 100644
--- a/lib/impl/NollupContext.js
+++ b/lib/impl/NollupContext.js
@@ -39,6 +39,8 @@ module.exports = {
     create: function (options) {
         if (!options.plugins) {
             options.plugins = [];
+        } else {
+            options.plugins = options.plugins.filter(plugin => Boolean(plugin));
         }
 
         if (!options.output) {
```

**Comment by PepsRyuu** [comment] 2019-11-15 13:10
Hey @ankon! Thanks for reporting the issue and for the patch proposal.

This can certainly be added. Will add this as soon as possible. Can you outline what other issues you've stumbled across as well? I'm very interested in getting Nollup to work for as many setups as possible.

**Comment by PepsRyuu** [comment] 2019-11-15 13:31
Released the patch in ```0.8.5```

**Comment by ankon** [comment] 2019-11-15 13:34
I see a bunch of `resolve: Not implemented` and `getModuleInfo: Not implemented`.

There are also a few of these:
~~~~
ParseError: node_modules/js-cookie/src/js.cookie.js
TypeError: Cannot read property 'isEntry' of undefined
    at Object.transformAndCheckExports (/Users/andreas/project/collaborne-polaris-app/node_modules/rollup-plugin-commonjs/dist/rollup-plugin-commonjs.cjs.js:779:89)
    at Object.transform (/Users/andreas/project/collaborne-polaris-app/node_modules/rollup-plugin-commonjs/dist/rollup-plugin-commonjs.cjs.js:842:48)
    at callPluginMethod (/Users/andreas/project/nollup/lib/impl/PluginLifecycle.js:24:37)
    at Object.transform (/Users/andreas/project/nollup/lib/impl/PluginLifecycle.js:170:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at parse (/Users/andreas/project/nollup/lib/index.js:93:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
~~~~

I suspect these related to the warnings rollup produces:
~~~~
node_modules/amazon-cognito-auth-js/es/CookieStorage.js
set is not exported by node_modules/js-cookie/src/js.cookie.js
45: 
46:   CookieStorage.prototype.setItem = function setItem(key, value) {
47:     Cookies.set(key, value, {
                ^
48:       path: this.path,
49:       expires: this.expires,
~~~~

**Comment by PepsRyuu** [comment] 2019-11-15 13:37
Thanks for the details! I plan to implement missing plugin methods and hooks as soon as possible. The most common features have been implemented so far. Can you show me a copy of your ```rollup.config.js```? Would like to know specifically which plugins are throwing the messages so I can improve compatibility.

**Comment by ankon** [comment] 2019-11-15 13:39
```
import { sep as FILE_SEPARATOR } from 'path';

import resolve from 'rollup-plugin-node-resolve';
import common from 'rollup-plugin-commonjs';
import copy from 'rollup-plugin-copy';
import serve from 'rollup-plugin-serve';
import { terser } from 'rollup-plugin-terser';

import typescript from '@wessberg/rollup-plugin-ts';

// Root directory, must be empty or have a trailing slash
const ROOT = process.env.ROOT || '';

export default {
	input: 'elements/app/container.ts',
	output: {
		dir: `build/${ROOT}`,
		format: 'esm',
		sourcemap: process.env.NODE_ENV !== 'production',
		sourcemapPathTransform: sourcePath => sourcePath.replace(`..${FILE_SEPARATOR}`, `.${FILE_SEPARATOR}`),
	},
	plugins: [
		typescript(),
		common({
			exclude: ['node_modules/marked/**'],
		}),
		resolve(),
		(process.env.NODE_ENV === 'production' && terser()),
		copy({targets: [...]}),
		process.env.PORT && process.env.ROLLUP_WATCH ? serve({
			open: false,
			contentBase: 'build/',
			port: process.env.PORT,
			verbose: true,
			historyApiFallback: false,
			historyApiFallback: `/${ROOT}index.html`,
		}) : undefined,
	],
};
```

(Trimmed a bit)

**Comment by PepsRyuu** [comment] 2019-11-15 13:45
Looks like the commonjs plugin has changed significantly since I've last checked. I'll fix compatibility with that plugin as soon as possible.

As a workaround, have you tried ```rollup-plugin-commonjs-alternate```?

**Comment by ankon** [comment] 2019-11-15 13:50
Nope. I'm fairly new in this rollup world still, so we basically picked whatever-first-worked. Will have a look, thanks!

**Comment by PepsRyuu** [comment] 2019-11-15 13:53
Just to clarify in that case. ```rollup-plugin-commonjs``` would be the most commonly used plugin that would have the most compatibility for CommonJS modules. I wrote ```rollup-plugin-commonjs-alternate``` because at the time, the standard plugin was incompatible with HMR (not sure if it still is, need to take a look and see). It might though unblock you at the moment while I work on getting the updated plugin working again.

**Comment by ankon** [comment] 2019-11-15 13:58
Right. 

Now, with that replacement done: No more "not implemented" for resolve/getModuleInfo, and the cookie.js parts are also not appearing - instead it does report that it compiles things!

... it also is quite slow, so I'll see over the next days where and how this could maybe work. My main goal is now is look for potentially faster alternatives than doing a build + serve cycle.

**Comment by PepsRyuu** [comment] 2019-11-15 14:04
Awesome to hear it's working!

Do you have any metrics on the build times? Initial build time, rebuild times, module count and file sizes? Unfortunately using CJS can be sluggish at times especially for larger modules, because it has to scan the entire code for uses of ```require``` and ```exports```. If possible always prefer ESM versions of code as they'll be significantly quicker to parse.

**Comment by PepsRyuu** [comment] 2019-11-22 14:29
```resolve```, ```getModuleInfo``` and more have all been implemented, and released in ```0.9.0```.

**Comment by charlag** [comment] 2019-11-25 16:58
Hi
I try out nollup for https://github.com/tutao/tutanota and I stumble upon an error with rollup commonjs plugin

So I wanted to ask if known compatibility issues were resolved. 

```
TypeError: importee.endsWith is not a function
    at Object.resolveId (/home/ivk/dev/repositories/tutanota-3/node_modules/rollup-plugin-commonjs/dist/rollup-plugin-commonjs.cjs.js:141:36)
    at callPluginMethod (/home/ivk/dev/repositories/tutanota-3/node_modules/nollup/lib/impl/PluginLifecycle.js:23:37)
    at callPluginCompileMethod (/home/ivk/dev/repositories/tutanota-3/node_modules/nollup/lib/impl/PluginLifecycle.js:75:27)
    at parse (/home/ivk/dev/repositories/tutanota-3/node_modules/nollup/lib/index.js:114:23)
```

**Comment by PepsRyuu** [comment] 2019-11-25 17:08
Hi @charlag 

As far as I know, in my testing, that plugin works fine. Not entirely what would be causing that error. If you have a more simple example I can have a look. Do you have exact steps to replicate the problem and I can confirm compatibility?

**Comment by charlag** [comment] 2019-11-25 18:50
I tried to adapt this code:
https://github.com/tutao/tutanota/blob/rollup/make.js#L145

And here's how the plugin is used:
https://github.com/tutao/tutanota/blob/rollup/buildSrc/RollupConfig.js#L27

I can try to make more narrow example

**Comment by PepsRyuu** [comment] 2019-11-26 15:00
Alternatively if you can provide the exact steps that will show the error, then I can have a look.

**Comment by Haroenv** [comment] 2020-01-07 14:26
endsWith might be node version

**Closed** 2020-05-17 10:02 UTC
